### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Tptuaazn** [katorlys/Spigot-CustomConfig#2]
Can you write a method or do something to make config auto update if outdated?

**Comment by katorly** [comment]
This should be achieved in your plugin, not in this ConfigReader.  

---
One possible solution:  
Put a line like this in the last line of your `config.yml`:  
```yaml
config-version: 1.0 #Do not modify this value!
```
And the value may be your plugin version.  

Then, you may get and check if the value is equal to your current plugin version on plugin enable.  
If the value is not latest, rename the file to `config_old.yml` or whatever and do `saveDefaultConfig()`.

**Comment by Tptuaazn** [comment]
I call the reload method with `Main.config.reloadConfig();` in my command class. I did the same as you instructed. But after executing nothing changed?.  Did I do anything wrong?

**Comment by katorly** [comment]
why reloadConfig()?

**Comment by katorly** [comment]
use `getConfig()` to get the value,  
and then use `renameTo`, which is from java.io.file

**Comment by Tptuaazn** [comment]
No.  I created a reload command but it doesn't seem to work. I have tried so many ways :(.

**Comment by Tptuaazn** [comment]
https://github.com/Tptuaazn/Heal
I don't know where I went wrong.

**Comment by Tptuaazn** [comment]
nvm i already know the problem
